version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectflow
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile # Path to the Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/projectflow?schema=public
      - JWT_SECRET=your_secret
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["node", "worker/cron.js"]
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/projectflow?schema=public
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api